In [1]:
import pandas as pd
import matplotlib.pyplot as plt

/tmp/ipykernel_28487/1492400551.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv('../DatosPrueba/Generacion_(kWh)_2023.csv' , header=2)

In [3]:
df

,Fecha,Recurso,Código Recurso,Tipo Generación,Combustible,Código Agente,Tipo Despacho,Es Menor,Clasificación,0,...,15,16,17,18,19,20,21,22,23,Version
0,2023-01-01 00:00:00,AGPE - ECOPETROL LA HORMIGA,2XXR,TERMICA,GAS,GECG,NO DESPACHADO CENTRALMENTE,NO,AUTOG PEQ. ESCALA,1.23,...,1.36,1.33,1.33,1.28,1.25,1.23,1.22,1.22,1.22,TX6
1,2023-01-01 00:00:00,AGUA FRESCA,AFR1,HIDRAULICA,AGUA,ADCG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,7254,...,7254,7256.4,7256.4,7257.6,7257.6,7264.8,7263.6,7264.8,7266,TX6
2,2023-01-01 00:00:00,ALEJANDRIA,2SDR,HIDRAULICA,AGUA,GALG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,8072,...,7980,8078,8024,7919,7988,7897,8058,9177,9798,TX6
3,2023-01-01 00:00:00,ALTO TULUA,ALTG,HIDRAULICA,AGUA,EPSG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,10108.8,...,10108.8,10112.4,10112.4,10112.4,10108.8,10112.4,10108.8,10108.8,10112.4,TX6
4,2023-01-01 00:00:00,AMAIME,AMA1,HIDRAULICA,AGUA,EPSG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,10289.18,...,8915.79,8881.58,8888.96,8884.47,3094.96,3634.5,10093.02,10110.6,10120.24,TX6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84472,2023-12-31 00:00:00,USAQUEN,USQ1,HIDRAULICA,AGUA,ENDG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,601.09,...,890.49,869.8,855.3,699.59,813.78,759.6,693.21,632.05,498.96,TX4
84473,2023-12-31 00:00:00,VENTANA A,VNTA,HIDRAULICA,AGUA,HDTG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,2459.56,...,-,-,-,-,-,-,-,-,-,TX4
84474,2023-12-31 00:00:00,VENTANA B,VNTB,HIDRAULICA,AGUA,HDTG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,-,...,2853.5,2822.39,2783.82,2753.98,2580.89,2416.75,2185.58,2123.71,2162.85,TX4
84475,2023-12-31 00:00:00,ZEUS,3E9I,HIDRAULICA,AGUA,CHZG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,3277.04,...,3236.87,3225.39,3196.7,2869.57,3104.87,3133.57,3110.61,3099.13,3087.65,TX4
84476,2023-12-31 00:00:00,ZIPAEMG 4,ZPA4,TERMICA,CARBON,ENDG,DESPACHADO CENTRALMENTE,NO,NORMAL,31473.74,...,31496.77,31497.72,31511.9,31481.09,31477.83,31446.11,31181.01,31118.34,31484.47,TX4

In [4]:
#Convertir el Campo fecha Operacion en Tipo Fecha
df['Fecha'] = pd.to_datetime(df['Fecha'])

In [5]:
#Sacar el Mes de la fecha 
df['Mes'] = df['Fecha'].dt.month

In [6]:
#Cantidad de generacion por mes
generacion_total_mes = df.groupby('Mes')['Combustible'].count()

In [7]:
generacion_total_mes

Mes
1     6567
2     5970
3     6669
4     6422
5     6932
6     7103
7     7449
8     7521
9     7140
10    7571
11    7351
12    7782
Name: Combustible, dtype: int64

In [8]:
#cantidad de generacion ordenado por mes y por fuente
generacion_fuente_mes = df.groupby(['Mes', 'Combustible'])['Combustible'].count()

In [9]:
generacion_fuente_mes

Mes  Combustible
1    ACPM              1
     AGUA           4063
     BAGAZO          394
     BIOGAS          106
     CARBON          276
                    ...
12   COMBUSTOLEO      27
     GAS             722
     GAS NI          141
     RAD SOLAR      1798
     VIENTO           62
Name: Combustible, Length: 130, dtype: int64

In [10]:
#calculamos el porcentaje de participacion de cada fuente (mensual)
porcentaje_participacion = (generacion_fuente_mes / generacion_total_mes)*100

In [11]:
porcentaje_participacion

Mes  Combustible
1    ACPM            0.015228
     AGUA           61.869956
     BAGAZO          5.999695
     BIOGAS          1.614131
     CARBON          4.202832
                      ...
12   COMBUSTOLEO     0.346955
     GAS             9.277821
     GAS NI          1.811874
     RAD SOLAR      23.104600
     VIENTO          0.796710
Name: Combustible, Length: 130, dtype: float64

In [12]:
#Creacion de nueva tabla
new_table = porcentaje_participacion.unstack().fillna(0)

In [13]:
new_table

Combustible,ACPM,AGUA,BAGAZO,BIOGAS,CARBON,COMBUSTOLEO,CRUDO,GAS,GAS NI,JET-A1,RAD SOLAR,VIENTO
Mes,,,,,,,,,,,,
1,0.015228,61.869956,5.999695,1.614131,4.202832,0.060911,0.045683,10.522309,0.000000,0.015228,14.237856,1.416172
2,0.268007,58.643216,6.817420,1.859296,5.427136,0.100503,0.050251,9.748744,0.050251,0.000000,15.628141,1.407035
3,0.059979,61.508472,6.612686,1.409507,3.343830,0.089969,0.000000,8.936872,0.000000,0.000000,16.644175,1.394512
4,0.077857,62.052320,5.683588,1.012146,2.896294,0.140143,0.000000,8.533167,0.031143,0.000000,18.171909,1.401433
5,0.144259,59.578765,4.125793,1.053087,5.337565,0.158684,0.100981,10.285632,0.288517,0.000000,17.585113,1.341604
6,0.140786,57.144868,5.434324,1.154442,5.040124,0.112628,0.042236,9.629734,0.774321,0.014079,19.245389,1.267070
7,0.174520,54.584508,5.638341,1.503558,5.866559,0.107397,0.000000,10.565177,0.147671,0.000000,20.163780,1.248490
8,0.292514,54.460843,5.424811,1.289722,5.770509,0.358995,0.053184,9.998670,0.771174,0.013296,20.329743,1.236538
9,0.280112,51.946779,5.630252,1.428571,6.134454,0.280112,0.504202,10.434174,1.596639,0.000000,20.504202,1.260504
10,0.766081,52.714305,5.151235,1.360454,6.168274,0.013208,0.594373,10.460969,1.320829,0.013208,20.512482,0.924581
11,0.993062,53.081213,4.366753,1.509999,5.128554,0.435315,0.802612,10.651612,0.761801,0.000000,21.452864,0.816215
12,0.732460,51.246466,5.397070,1.464919,5.821126,0.346955,0.000000,9.277821,1.811874,0.000000,23.104600,0.796710

In [14]:
#Cambiar nombre a las columnas
new_table =new_table.rename(columns={'ACPM': 'Porcentaje ACPM', 'AGUA': 'Porcentaje Agua', 'BAGAZO': 'Porcentaje Bagazo',
                                        'BIOGAS': 'Porcentaje Biogas', 'CARBON': 'Porcentaje Carbon', 'COMBUSTOLEO': 'Porcentaje Combustoleo',
                                        'CRUDO': 'Porcentaje Crudo', 'GAS': 'Porcentaje Gas', 'GAS NI': 'Porcentaje Gas NI',
                                        'JET-A1': 'Porcentaje JET-A1', 'RAD SOLAR': 'Porcentaje RAD SOLAR', 'VIENTO': 'Porcentaje Viento'})

In [15]:
new_table

Combustible,Porcentaje ACPM,Porcentaje Agua,Porcentaje Bagazo,Porcentaje Biogas,Porcentaje Carbon,Porcentaje Combustoleo,Porcentaje Crudo,Porcentaje Gas,Porcentaje Gas NI,Porcentaje JET-A1,Porcentaje RAD SOLAR,Porcentaje Viento
Mes,,,,,,,,,,,,
1,0.015228,61.869956,5.999695,1.614131,4.202832,0.060911,0.045683,10.522309,0.000000,0.015228,14.237856,1.416172
2,0.268007,58.643216,6.817420,1.859296,5.427136,0.100503,0.050251,9.748744,0.050251,0.000000,15.628141,1.407035
3,0.059979,61.508472,6.612686,1.409507,3.343830,0.089969,0.000000,8.936872,0.000000,0.000000,16.644175,1.394512
4,0.077857,62.052320,5.683588,1.012146,2.896294,0.140143,0.000000,8.533167,0.031143,0.000000,18.171909,1.401433
5,0.144259,59.578765,4.125793,1.053087,5.337565,0.158684,0.100981,10.285632,0.288517,0.000000,17.585113,1.341604
6,0.140786,57.144868,5.434324,1.154442,5.040124,0.112628,0.042236,9.629734,0.774321,0.014079,19.245389,1.267070
7,0.174520,54.584508,5.638341,1.503558,5.866559,0.107397,0.000000,10.565177,0.147671,0.000000,20.163780,1.248490
8,0.292514,54.460843,5.424811,1.289722,5.770509,0.358995,0.053184,9.998670,0.771174,0.013296,20.329743,1.236538
9,0.280112,51.946779,5.630252,1.428571,6.134454,0.280112,0.504202,10.434174,1.596639,0.000000,20.504202,1.260504
10,0.766081,52.714305,5.151235,1.360454,6.168274,0.013208,0.594373,10.460969,1.320829,0.013208,20.512482,0.924581
11,0.993062,53.081213,4.366753,1.509999,5.128554,0.435315,0.802612,10.651612,0.761801,0.000000,21.452864,0.816215
12,0.732460,51.246466,5.397070,1.464919,5.821126,0.346955,0.000000,9.277821,1.811874,0.000000,23.104600,0.796710

In [16]:
new_table.to_csv('pregunta4_tabla.csv')